name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build frontend image
      run: |
            cd client
            docker build -t front:latest .
    - name: Build backend image
      run: |
           cd server
           docker build -t backend:latest .
    - name: Run docker compose
      run: |
            docker-compose -f  docker-compose.yml up -d
