name: Docker Image CI

on: 
  workflow_dispatch:
     
  push:
    branches: [ "main" ]
  
  
  
jobs:

  build_front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build frontend image
      run: |
            cd client
            docker build -t front:latest .
            
  build_back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build backend image
      run: |
           cd server
           docker build -t backend:latest .

  publish_localhost:
    runs-on: ubuntu-latest
    needs: [build_front,build_back]
    steps:
    - uses: actions/checkout@v2
    - name: Run docker compose
      run: |
            docker-compose -f  docker-compose.yml up -d 
            sleep 10
            docker ps
            sleep 5
            curl localhost:8080
            
 
