name: Docker Image CI

on: 
  workflow_dispatch:
     
  push:
    branches: [ "main" ]
  
  
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build frontend image
      run: |
            cd client
            docker build -t front:latest .
    - name: Build backend image
      run: |
           cd server
           docker build -t backend:latest .
    - name: Run docker compose
      run: |
            docker-compose -f  docker-compose.yml up -d 
            
  publish_localhost:
    runs-on: ubuntu-latest
    
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Expose local server with ngrok
        run: |
          ngrok http 8080 http 8081 > /dev/null & # Expose both ports
          sleep 5 # Wait for ngrok to start
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok URL: $NGROK_URL"
