name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
            cd client
            docker build -t front:latest .
    - name: Build backend image
      run: |
           docker build -t backend:latest server/Dockerfile server
