name: Build app without docker
on: 
   workflow_dispatch:
   push:
      branches: ["main"]





jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['10.x', '12.x','14.x']
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install dependencies
        working-directory: ./client
        run: |
             npm ci
             npm run build
             npm install -g serve
      - name: Start app
        run: |
              serve -s build -l 8080
              curl localhost:8080

              
          
   
