name: Node.js CI

on:
  workflow_dispatch:
 # push:
  #  branches:
  #    - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js

      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: client
      run: npm ci

    - name: Build
      working-directory: client
      run: npm run build
      env:
        CI: false

    - name: Install serve
      working-directory: client
      run: npm install -g serve

    - name: Start server
      working-directory: client
      run: serve -s build -l 8080
